CREATE TABLE nursing (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    starttime TEXT NOT NULL,
    endtime TEXT NOT NULL,
    duration INTEGER NOT NULL,
    rightside INTEGER NOT NULL,
    leftside INTEGER NOT NULL,
    userId INTEGER REFERENCES users(id)

);